### ISSUE TITLE
Please update to 2.6.0

### ISSUE THREAD

**Issue by keligijus** [jm-david/emoji-mart-vue#10]
It uses v3 of Emojione. ❤️ 

https://github.com/missive/emoji-mart/releases/tag/v2.6.0

**Comment by xuzili1993** [comment]
now is v2.6.1 😄

**Comment by keligijus** [comment]
@xuzili1993 impossible to keep up :D happy with any version, as long as it has the current Emojione version.

**Comment by jm-david** [comment]
Doneee! Let me know if you guys encounter any problems/issues with the new version :)
