### ISSUE TITLE
[Question] How do you replace the emojis in your HTML?

### ISSUE THREAD

**Issue by hfalucas** [jm-david/emoji-mart-vue#11]
Just starting using this plugin, love the fact that is not opinionated but unfortunately, I'm having some troubles.

I have successfully been able to add the emojis to my HTML string, the problem is rendering them.
How do you replace the emojis in your HTML using the `Emoji` component?

This is what I have so far: https://github.com/hfalucas/emoji-mart-vue-issue

**Comment by jm-david** [comment]
Hmm well the simplest solution would be to just use the native emoji and append that to the string. However, if you're looking to dynamically replace a string with Emoji components then I think the best way would be to use a render function. Something like this maybe...
https://gist.github.com/jm-david/7f98c3ee4fe235c596cff26d7aa26b7b

**Comment by hfalucas** [comment]
Thank you so much for your example, I will give it a try as soon as I can 👍
