### ISSUE TITLE
Some emoji shortnames do not match with Emojione

### ISSUE THREAD

**Issue by keligijus** [jm-david/emoji-mart-vue#15]
If you look at [emojione emoji.json](https://raw.githubusercontent.com/emojione/emojione/master/emoji.json) you'll see that most countries have a shortname of `:flag_<country-code>:` whilst Emoji Mart is using `:flag-<country-code>:`. So one is using underscores while the other is using dashes.

There are more mismatches. Can I do anything to fix this?

**Comment by jm-david** [comment]
Ahh interesting, I'm not sure why they would be different 🤔  The code to generate the emoji data is part if the parent react library (https://github.com/missive/emoji-mart) so I'd create your issue there and then once they update it I can merge it back into this project 👍
