### ISSUE TITLE
Picker has incorrect styling in IE11 / Edge

### ISSUE THREAD

**Issue by ReneS1991** [jm-david/emoji-mart-vue#19]
When the picker is opened in IE11/Edge the styling is incorrect. This problem only occurs for emoji-mart-vue, not for emoji-mart.

The following problems are found:
1) The searchbar has a height of 0px and is therefore overlapped by the emoji-list.
2) The categories have a height of 0px and are therefore overlapped by the searchbar & emoji-list.
3) The categories are missing the images. As you can see in the screenshot the SVG's for the categories are missing their <path> elements.

Would be awesome if it could be fixed anytime soon. Thanks in advance! :)

![screen shot 2018-06-05 at 14 37 33](https://user-images.githubusercontent.com/17007821/40976306-071682d0-68ce-11e8-8fb6-ef8635c8d822.png)

**Comment by jhlee8804** [comment]
+1

**Comment by ReneS1991** [comment]
@jm-david Any news on this? :)
