### ISSUE TITLE
onClick not working

### ISSUE THREAD

**Issue by shaunc869** [jm-david/emoji-mart-vue#24]
Hi!

I realize this is a rather basic question, so I apologize, but this doesn't seem to work:

`<picker v-show="showEmojis" set="emojione" :style="{ position: 'absolute', bottom: '120px', right: '80px' }" title="" onClick="nsertEmoji" />`

It renders great and hides/shows fine, but the onclick won't fire for the life of me, can you show a full example of how to properly define and call the methods? Thanks!

**Comment by ReneS1991** [comment]
You shouldn't assign it to 'onClick' but to '@select', as in the following example:

`<picker v-show="showEmojis" set="emojione" :style="{ position: 'absolute', bottom: '120px', right: '80px' }" title="" @select="nsertEmoji" />`

And an additional note, if your code was a copy-paste, you got a typo:
'nsertEmoji' => 'insertEmoji'

**Comment by shaunc869** [comment]
That worked perfectly, thanks!

**Comment by jm-david** [comment]
Thanks, I've updated the readme to properly reflect the events provided by the Emoji component.
