### ISSUE TITLE
fallbackEmojiStyles 

### ISSUE THREAD

**Issue by origo27** [jm-david/emoji-mart-vue#27]
Hi, I would like to know if there is any way that I could pull this object when clicking on an emoji in the picker?  or how can I add it in the Emoji Object obtained. 

![screen shot 2018-07-19 at 2 24 11 pm](https://user-images.githubusercontent.com/39117735/42936627-2bf8e0b0-8b7f-11e8-99d6-8fad2db1da91.png)

**Comment by jm-david** [comment]
Hmm not ideal, but you could access it by rendering the `Emoji` component and then using a `ref` prop to access the component instance directly. Is there a reason why you're unable to use the Emoji component to handle the rendering?

**Comment by origo27** [comment]
we're trying to convert markdown formatted text containing emoj.colons and inserting emoji component in between the text does not seem possible. 

example:
`" *Hey* rigo :smile: , how are you?"` should render as :  

`<strong>Hey</strong> rigo <img style="display:inline-block;background-image:url(https://a.slack-edge.com/c00d19/img/emoji_2017_12_06/sheet_apple_64_indexed_256.png); background-position:58.8235294117647% 54.90196078431372%; background-size:5200%; width:24px; height:24px" /> how are you?`

**Comment by jm-david** [comment]
Ahh okay, do you think something like this would work? https://gist.github.com/jm-david/7f98c3ee4fe235c596cff26d7aa26b7b

**Comment by jm-david** [comment]
Yep should do! :)

**Comment by origo27** [comment]
thanks david! going to try it. I have another question though, for EmojiSearch, the mapping is using the native , how can I replace the display from native to the set sheet?  screenshot below:

![screen shot 2018-07-26 at 11 43 01 am](https://user-images.githubusercontent.com/39117735/43240438-14c1baa8-90c9-11e8-938f-b730fd8f9401.png)

**Comment by jm-david** [comment]
Are you using the Emoji component? Or just outputting the native emoji directly?

**Comment by origo27** [comment]
ah yes, i forgot i was display the native directly. thanks for the heads up. Using the emoji component now but it seems that it does not render the emoji:

![screen shot 2018-07-26 at 1 56 48 pm](https://user-images.githubusercontent.com/39117735/43244093-0aaf3e06-90dc-11e8-8049-51e1ba4dddd5.png)

however if i tried `:santa::skin-tone-3:` it displays the correct emoji :
![screen shot 2018-07-26 at 2 00 01 pm](https://user-images.githubusercontent.com/39117735/43244132-3673d68c-90dc-11e8-884a-78f3080f910a.png)

**Comment by origo27** [comment]
nvm, just needed an update. hehe thanks!
