### ISSUE TITLE
removing nativ emojis

### ISSUE THREAD

**Issue by manishkumar1683** [jm-david/emoji-mart-vue#28]
Hi ,
Thanks for this wonderful plug-in.
I am facing issue for rendering emojis in browsers.  I want to hide all those emojis which renders natively in browsers. Like some of the smilies rendered in black color. How to hide those from user selection.

Thanks,
Manish.

**Comment by jm-david** [comment]
Unfortunately I am not aware of a way to detect whether a given OS supports an emoji or not. I'd recommend using one of the emoji sets `<picker set="apple" />` to get a consistent result across platforms.
