### ISSUE TITLE
Picker component slowing down other Vue components

### ISSUE THREAD

**Issue by thoms17** [jm-david/emoji-mart-vue#29]
Hello,

First, congratulations for your work, it's really nice !

I'm using your emoji picker in a messaging project, and i'm having really low performances doing some trivial things.

For exemple, I'm using a textarea to type message to send with a v-model inside and i text entry is really slow. Otherwise, i have to click on a buddy to open the conversation i have with him, and in the same way, it takes like 2s to open the conversation, and in the performance monitor, i'm reaching 100% of CPU usage meanwhile. All this lags are happening while picker component is not opened or used. It's available if I click on a specific button but hidden if I don't. 

Commenting the picker component solved all of my problems, no more latency or anything else, my textarea is fluid, same as conversations opening. It would be a shame not to use it because I really appreciate how it works. I also find some way to avoid the latency using JQuery rather than vue directives but it's also a shame using JQuery while it's that simple with Vue. Even using an emty picker with no props is causing latency.

So I was wondering if there is not any performance issue in this component. 

Thanks

**Comment by MehrdadKhanzadeh** [comment]
Hey there! Same here! I was about to open a new issue for this, then I saw this! I have the exact same problem! With emoji picker, it gets really slow and I don't know what to do! It's almost unusable this way!

**Comment by s4tori** [comment]
Hi,

I'm experiencing the same issue... 
@thoms17 and @MehrdadKhanzadeh, can you try with emoji-mart-vue v2.5.3?
It's seems that performance problems have appeared since version 2.6.1 only.

A lot of commits have been made between version 2.5.3 and 2.6.1, and I don't have a lot of time to investigate. With version 2.5.3, emoji-mart-vue works very well.

**Comment by MehrdadKhanzadeh** [comment]
@s4tori Hi! Thanks! It worked for me!

**Comment by Serubin** [comment]
I'm having a similar issue. This version of emoji-mart fires some very costly event sequences. This was noticed during typing events on an unrelated input field. For some reason the emoji-mart plugin is creating and removing elements from the DOM along with doing some other costly and seemingly unnecessarily calculations.

The images below are the performance profile of original vue-emoji-mart followed by the emoji-mart-vue implementation.

<img width="412" alt="screen shot 2018-09-21 at 9 54 24 pm" src="https://user-images.githubusercontent.com/1234465/45912023-3809dc00-bde9-11e8-8a8c-226511e86410.png">
<img width="321" alt="screen shot 2018-09-21 at 9 55 42 pm" src="https://user-images.githubusercontent.com/1234465/45912024-3809dc00-bde9-11e8-8412-086ca2ae3fd4.png">

**Comment by marchofreason** [comment]
I'm experiencing this issue as well. Have tried to use Nimble-Picker and load only the messenger.json to see if this resolves it. Will try and revert to 2.5.x to see if this fixes the issue. 

Currently using `"emoji-mart-vue": "^2.6.4",`

**Comment by pmdarrow** [comment]
Still slow for me even after downgrading to 2.5.x. I will try to find some time to dig into what's causing the delays...

**Comment by zealotrahl** [comment]
2.6.6, still slow, call it with VueSax sidebar, and it freezes sidebar animation.

**Comment by Serubin** [comment]
We've started using this fork https://github.com/serebrov/emoji-mart-vue in production.

It's significantly faster and has been more consistent than this fork.
