### ISSUE TITLE
Lightest possible setup

### ISSUE THREAD

**Issue by andreasvirkus** [jm-david/emoji-mart-vue#34]
Hi,

I'm wondering what's the lightest possible setup (ie to display only native emojis) and to minimize the
initial load time after component has mounted. I know this is somewhat related to https://github.com/jm-david/emoji-mart-vue/issues/9, but I was wondering why I'm seeing a long loading time even though I'm not providing any set for the component and setting `:native="true"` for the picker?

My setup currently:
```
<picker
      v-if="showPicker"
      v-click-outside="closePicker"
      :native="true"
      color="#475DE5"
      :showSkinTones="false"
      :showPreview="false"
      :sheetSize="16"
      @select="addEmoji"
      @keyup.esc.native="closePicker"
      :pickerStyles="pickerStyles"/>
```

I also tried the "visually hidden mount" hack but that's not really a favourable work-around 😞

**Comment by EyMaddis** [comment]
You are trying to do get Picker from a function, which does not work.
This does:
`const Picker = () => import('emoji-mart-vue').then(({ Picker }) => Picker)`

**Comment by dimer22zhc** [comment]
how do i prevent  native emoji to joying up every fkin time
